# Generated by Django 3.2.2 on 2021-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.TextField(verbose_name='full_link')),
                ('short_link', models.TextField(verbose_name='short_link')),
            ],
        ),
    ]
